# @package _global_
aug:
  tfms:
    hue_sat:
      _target_: albumentations.augmentations.transforms.HueSaturationValue
      hue_shift_limit: 0.2
      sat_shift_limit: 0.2
      val_shift_limit: 0.2
      p: 0.9

    brightness_contrast:
      _target_: albumentations.augmentations.transforms.RandomBrightnessContrast
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.9

    to_gray:
      _target_: albumentations.augmentations.transforms.ToGray
      p: 0.01

    flip:
      _target_: albumentations.augmentations.transforms.Flip
      always_apply: true

    cutout:
      _target_: albumentations.augmentations.transforms.Cutout
      num_holes: 8
      max_h_size: 64
      max_w_size: 64
      fill_value: 0
      p: 0.5

    to_tensor:
      _target_: albumentations.pytorch.transforms.ToTensorV2
      always_apply: true

  bbox_params:
    _target_: albumentations.core.composition.BboxParams
    format: pascal_voc
    label_fields:
      - labels